app/models/employee.py
# app/models/employee.py

"""
Represents an employee in the system.
    :param first: First name of the employee
    :param last: Last name of the employee
    :param team: Team the employee belongs to
    :param emp_id: Unique identifier for the employee
"""
class Employee:

    def __init__(self, first, last, team, emp_id):
        self.id = emp_id
        self.first = first
        self.last = last
        self.team = team

    @property
    def fullname(self):
        return f'{self.first} {self.last}'

    def __repr__(self):
        return f"Employee('{self.first}', '{self.last}', '{self.team}')"

    

app/routes/employees.py
# app/routes/employees.py

"""
Employee Management Routes

This module handles the management of employees, providing routes for:
- / (index): List all employees
- /add: Add a new employee
- /delete/<id>: Remove an employee
- /edit/<id>: Modify an existing employee's details
- /reveal_password/<id>: Display an employee's password
- /edit_password/<id>: Change an employee's password
- /update_role/<id>: Update an employee's role
"""

from flask import Blueprint, flash, render_template, request, redirect, url_for
from app.services import employee_service
from app.services.user_service import create_user, get_user_by_id
from flask_login import login_required, current_user
from werkzeug.security import check_password_hash
from app.services import employee_shift_service
employees_bp = Blueprint('employees', __name__)

# Helper function to check if the current user is a manager
def is_manager():
    return current_user.is_authenticated and hasattr(current_user, 'role') and current_user.role == 'manager'

@employees_bp.route('/')
@login_required
def index():
    employees_with_users = employee_service.get_all_employees_with_users()
    for emp in employees_with_users:
        print(f"Employee: {emp['employee'].fullname}, User ID: {emp['user_id']}")
    return render_template('employees/employees.html',
                           employees_with_users=employees_with_users,
                           active='employees',
                           is_manager=is_manager())

@employees_bp.route('/add', methods=['POST'])
@login_required
def add_employee():
    if not is_manager():
        flash('Only managers can add employees.', 'error')
        return redirect(url_for('employees.index'))

    first_name = request.form['first_name']
    last_name = request.form['last_name']
    team = request.form['team']
    username = request.form['username']
    password = request.form['password']
    employee_id = employee_service.add_employee(first_name, last_name, team)
    
    if employee_id:
        if create_user(username, password, employee_id):
            flash('Employee and user account created successfully', 'success')
        else:
            flash('Employee created, but user account creation failed, suppressing employee', 'warning')
            employee_service.delete_employee(employee_id)
    else:
        flash('Failed to create employee', 'error')
    
    return redirect(url_for('employees.index'))

@employees_bp.route('/delete/<int:id>')
@login_required
def delete_employee(id):
    if not is_manager():
        flash('Only managers can delete employees.', 'error')
        return redirect(url_for('employees.index'))
    
    employee_service.delete_employee(id)
    flash('Employee deleted successfully.', 'success')
    return redirect(url_for('employees.index'))

@employees_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_employee(id):
    if not is_manager():
        flash('Only managers can edit employee information.', 'error')
        return redirect(url_for('employees.index'))

    employee = next(
        (e for e in employee_service.get_all_employees() if e.id == id), None)
    if request.method == 'POST':
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        team = request.form['team']

        employee_service.update_employee(id, first_name, last_name, team)
        flash('Employee updated successfully.', 'success')
        return redirect(url_for('employees.index'))
    return render_template('employees/edit_employee.html', employee=employee)

@employees_bp.route('/reveal_password/<int:id>', methods=['POST'])
@login_required
def reveal_password(id):
    if not is_manager():
        flash('Only managers can reveal passwords.', 'error')
        return redirect(url_for('employees.index'))

    employee_with_user = next((e for e in employee_service.get_all_employees_with_users() if e['user_id'] == id), None)
    if employee_with_user and employee_with_user['password_hash']:
        user = get_user_by_id(employee_with_user['user_id'])
        return render_template('employees/employee_pwd.html', employee=employee_with_user['employee'], password=user.password)
    return redirect(url_for('employees.index'))

@employees_bp.route('/edit_password/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_password(id):
    if not is_manager():
        flash('Only managers can edit passwords.', 'error')
        return redirect(url_for('employees.index'))

    employee_with_user = next((e for e in employee_service.get_all_employees_with_users() if e['employee'].id == id), None)
    if employee_with_user:
        if request.method == 'POST':
            new_password = request.form['new_password']
            user = get_user_by_id(employee_with_user['user_id'])
            user.password = new_password
            print(f"New encrypted password: {user.password_hash}")
            print(f"New encrypted password: {user.password}")
            employee_service.save_new_password(user.password_hash, employee_with_user['user_id'])
            flash('Password updated successfully.', 'success')
            return redirect(url_for('employees.index'))
        return render_template('employees/employee_pwd.html', employee=employee_with_user['employee'], edit_mode=True)
    return redirect(url_for('employees.index'))

@employees_bp.route('/update_role/<int:id>', methods=['POST'])
@login_required
def update_role(id):
    if not is_manager():
        flash('Only managers can update roles.', 'error')
        return redirect(url_for('employees.index'))

    new_role = request.form['role']
    if employee_service.update_user_role(id, new_role):
        flash('Role updated successfully', 'success')
    else:
        flash('Failed to update role', 'error')
    return redirect(url_for('employees.index'))

@employees_bp.route('/off_days', methods=['GET'])
@login_required
def off_days():
    employees = employee_service.get_all_employees()
    off_days_data = []

    for employee in employees:
        total_off_days = 20  # Total allowed off days
        approved_off_days = employee_shift_service.get_approved_off_days(employee.id)
        remaining_off_days = total_off_days - approved_off_days

        off_days_data.append({
            'employee_name': employee.fullname,
            'approved_off_days': approved_off_days,
            'remaining_off_days': remaining_off_days
        })

    return render_template('employees/off_days.html', off_days_data=off_days_data)

app/templates/employees/edit_employee.html
<!-- app/templates/edit_employee.html -->
{% extends 'layout.html' %}

{% block title %}<h1>Edit Employee</h1>{% endblock %}

{% block content %}
<form action="{{ url_for('employees.edit_employee', id=employee.id) }}" method="post">
    <div class="form-group">
        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" id="first_name" value="{{ employee.first }}" required>
    </div>
    <div class="form-group">
        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name" id="last_name" value="{{ employee.last }}" required>
    </div>
    <div class="form-group">
        <label for="team">Last Name:</label>
        <input type="text" name="team" id="team" value="{{ employee.team }}" required>
    </div>
    <button type="submit">Update Employee</button>
    <a href="{{ url_for('employees.index') }}" class="cancel-button">Cancel</a>
</form>

{% endblock %}

app/templates/employees/employee_pwd.html
{% extends 'layout.html' %}

{% block title %}<h1>Reveal Password</h1>{% endblock %}

{% block content %}
<div>
    <h2>Password for {{ employee.fullname }}</h2>
    
    {% if not edit_mode %}
    <form>
        <div class="form-group">
        <label for="name">Password:</label>
        <span class= "fixed-select-display" id="shift_name"> {{ password }}</span>
        </div>
        <a href="{{ url_for('employees.edit_password', id=employee.id) }}" class="blue-button">Edit</a>
        <a href="{{ url_for('employees.index') }}" class="cancel-button">Back to Employees</a>
    </form>

    {% else %}
    
    <form method="POST">
        <div class="form-group">
            <label for="new_password">New Password:</label>
            <input type="password" name="new_password" id="new_password" required>
        </div>
        <button type="submit" class="blue-button">Update Password</button>
        <a href="{{ url_for('employees.index') }}" class="cancel-button">Cancel</a>
    </form>

    {% endif %}

    
</div>



{% endblock %}

app/templates/employees/employees.html
<!-- app/templates/employees.html -->
{% extends 'layout.html' %}

{% block title %}<h1>Employees</h1>{% endblock %}

{% block content %}

<!-- Display Flash Messages -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="flash-messages">
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}

{% if is_manager %}
<div>
    <h2>Add New Employee</h2>
    <form action="{{ url_for('employees.add_employee') }}" method="post">
        <div class="form-group">
            <div class="text-field-container">
                <input type="text" name="first_name" placeholder="First name" required>
                <input type="text" name="last_name" placeholder="Last name" required>
            </div>
            <div class="text-field-container">
                <input type="text" name="team" placeholder="Team name" required>
            </div>
            <div class="text-field-container">
                <input type="text" name="username" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
            </div>
        </div>
        <button type="submit">Add Employee</button>
    </form>
</div>
{% endif %}

<div>
    <h2>Employee List</h2>
    <table>
        <thead>
            <tr>
                <th>Employee</th>
                <th>Team</th>
                <th>Username</th>
                <th>Password</th>
                <th>Role</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in employees_with_users %}
                <tr id="employee-{{ item.employee.id }}">
                    <td>{{ item.employee.fullname }}</td>
                    <td>{{ item.employee.team }}</td>
                    <td>{{ item.username or 'N/A' }}</td>
                    
                    {% if item.user_id %}
                    <td>
                        {% if is_manager %}
                            <form method="POST" action="{{ url_for('employees.reveal_password', id=item.user_id) }}" class="in_table">
                                <button type="submit">Reveal Password</button>
                            </form>
                        {% else %}
                            <p>Restricted</p>
                        {% endif %}
                    </td>
                    <td>
                        {% if is_manager %}
                            <form method="POST" action="{{ url_for('employees.update_role', id=item.user_id) }}" class="in_table">
                                <select name="role" onchange="this.form.submit()">
                                    <option value="adc_employee" {% if item.role == 'adc_employee' %}selected{% endif %}>ADC Employee</option>
                                    <option value="manager" {% if item.role == 'manager' %}selected{% endif %}>Manager</option>
                                </select>
                            </form>
                        {% else %}
                            <p>{{ item.role }}</p>
                        {% endif %}
                    </td>
                    {% else %}
                        <td>
                            <p>No user account</p>
                        </td>
                        <td>
                            <p>No user account</p>
                        </td>
                    {% endif %}
                    <td class="action-column">
                        {% if is_manager %}
                            <a href="{{ url_for('employees.edit_employee', id=item.employee.id) }}" class="edit-button" title="Edit">Edit</a>
                        {% else %}
                            <span>-</span>
                        {% endif %}
                    </td>
                    <td class="action-column">
                        {% if is_manager %}
                            <a href="{{ url_for('employees.delete_employee', id=item.employee.id, next=request.path) }}" title="Delete" 
                            onclick="return confirm('Are you sure you want to delete the employee {{ item.employee.fullname }}?');" class="delete-button">Delete</a>
                        {% else %}
                            <span>-</span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<style>
    .flash-messages {
        margin-bottom: 20px;
    }
    .alert {
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 10px;
    }
    .alert-success {
        background-color: #d4edda;
        color: #155724;
        border: 1px solid #c3e6cb;
    }
    .alert-error {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
    }
</style>

{% endblock %}

app/templates/employees/off_days.html
{% extends 'layout.html' %}

{% block title %}<h1>Employee Off Days</h1>{% endblock %}

{% block content %}
<h2>Off Days Overview</h2>

<table class="table">
    <thead>
        <tr>
            <th>Employee Name</th>
            <th>Approved Off Days</th>
            <th>Remaining Off Days</th>
        </tr>
    </thead>
    <tbody>
        {% for data in off_days_data %}
        <tr>
            <td>{{ data.employee_name }}</td>
            <td>{{ data.approved_off_days }}</td>
            <td>{{ data.remaining_off_days }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}