app/routes/my_shifts.py
# app/routes/my_shifts.py

"""
My Shifts Management Routes

This module handles the management of an employee's own shifts, providing routes for:
- / (index): List all shifts for the current employee
- /assign: Assign a new shift to the current employee
- /delete/<id>: Remove a shift assignment
- /edit/<id>: Modify an existing shift assignment
- /update_actual_times/<id>: Update actual start and end times for a shift
"""

from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from app.services import employee_shift_service, employee_service, shift_service, my_shifts_service
from dateutil.relativedelta import relativedelta

from app.utils.time_utils import get_month_dates, calculate_month_offset, get_month_calendar
from datetime import datetime

my_shifts_bp = Blueprint('my_shifts', __name__)


@my_shifts_bp.route('/')
@login_required
def index():
    employee_id = current_user.employee_id
    shifts = shift_service.get_all_active_shifts()
    employee = employee_service.get_employee_by_id(employee_id)
    
    if not employee:
        flash(
            "Your account is not associated with an employee. Please contact the administrator.",
            "warning")
        employee_shifts = {'shifts': [], 'total_overtime': '00:00'}
    else:
        employee_shifts = my_shifts_service.get_employee_shifts_by_employee_id(employee_id)

    month_offset = int(request.args.get('month_offset', 0))
    target_date = datetime.now().date() + relativedelta(months=month_offset)
    calendar_weeks = get_month_calendar(target_date.year, target_date.month)
    
    # Organize shifts by date
    shifts_by_date = {}
    for emp_shift in employee_shifts['shifts']:
        shift_date = emp_shift['employee_shift'].date
        shifts_by_date[shift_date] = {
            'name': emp_shift['shift_name'],
            'bg_color': emp_shift['shift_bg_color'],
            'text_color': emp_shift['shift_text_color'],
            'request_status': emp_shift['employee_shift'].get_display_status(emp_shift['shift_name'])
        }

    return render_template('my_shifts/my_shifts.html',
                           employee_shifts=employee_shifts,
                           employee=employee,
                           shifts=shifts,
                           calendar_weeks=calendar_weeks,
                           target_date=target_date,
                           shifts_by_date=shifts_by_date,
                           month_offset=month_offset,
                           active='my_shifts',
                           username=current_user.username)


@my_shifts_bp.route('/assign', methods=['POST'])
@login_required
def assign_shift():
    employee_id = request.form['employee_id']
    shift_id = request.form['shift_id']
    date = request.form['date']
    month_offset = request.form.get('month_offset', 0)

    if employee_id and date:
        if shift_id:
            shift = shift_service.get_shift_by_id(shift_id)

            start_time = shift.start_time if shift.start_time else ""
            end_time = shift.end_time if shift.end_time else ""

            shift_name = shift.name.upper() if shift else ""

            # Clearly set Pending approval for OFF and REST shifts by normal users
            if shift_name in ['OFF', 'REST']:
                shift_type = shift_name
                approval_status = 'Pending'
            else:
                shift_type = 'Regular'
                approval_status = 'Approved'

            employee_shift_service.assign_shift(
                employee_id,
                shift_id,
                date,
                start_time,
                end_time,
                shift_type=shift_type,
                custom_details=None,
                approval_status=approval_status
            )
        else:
            employee_shift_service.delete_assignment_by_employee_and_date(employee_id, date)

    return redirect(url_for('my_shifts.index', month_offset=month_offset, employee_id=employee_id))



@my_shifts_bp.route('/delete/<int:id>')
def delete_assignment(id):
    employee_id = request.args.get('employee_id')
    employee_shift_service.delete_assignment(id)

    return redirect(url_for('my_shifts.index', employee_id=employee_id))


@my_shifts_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_assignment(id):
    if request.method == 'POST':
        employee_id = request.form['employee_id']
        shift_id = request.form['shift_id']
        date = request.form['date']

        if employee_shift_service.update_employee_shift(
                id, employee_id, shift_id, date):
            return redirect(url_for('my_shifts.index',
                                    employee_id=employee_id))
        else:
            flash('Failed to update my shift', 'error')

    employee_shift = employee_shift_service.get_employee_shift(id)
    employees = employee_service.get_all_employees()
    shifts = shift_service.get_all_shifts()

    return render_template('my_shifts/edit_my_shift.html',
                           employee_shift=employee_shift,
                           employees=employees,
                           shifts=shifts)


@my_shifts_bp.route('/update_actual_times/<int:id>', methods=['GET', 'POST'])
def update_actual_times(id):
    employee_shift_data = employee_shift_service.get_employee_shift(id)
    shift_start_time = employee_shift_data['shift_start_time']
    shift_end_time = employee_shift_data['shift_end_time']
    
    if employee_shift_data['employee_shift'].actual_start_time:
        actual_start_time = datetime.strptime(employee_shift_data['employee_shift'].actual_start_time, '%I:%M %p').strftime('%H:%M')
    elif shift_start_time:
        actual_start_time = datetime.strptime(shift_start_time, '%I %p').strftime('%H:%M')
    else:
        actual_start_time = shift_start_time
    if employee_shift_data['employee_shift'].actual_end_time:
        actual_end_time = datetime.strptime(employee_shift_data['employee_shift'].actual_end_time, '%I:%M %p').strftime('%H:%M')
    elif shift_end_time:
        actual_end_time = datetime.strptime(shift_end_time, '%I %p').strftime('%H:%M')
    else:
        actual_end_time = shift_end_time

    if employee_shift_data is None:
        flash('Employee shift not found', 'error')
        return redirect(url_for('my_shifts.index'))

    if request.method == 'POST':
        actual_start_time = request.form['actual_start_time']
        actual_end_time = request.form['actual_end_time']
        employee_id = request.form.get('employee_id')

        # Update the database with actual times
        if my_shifts_service.update_actual_times(id, actual_start_time,
                                                 actual_end_time):
            flash('Actual times updated successfully', 'success')
        else:
            flash('Failed to update actual times', 'error')

        return redirect(url_for('my_shifts.index', employee_id=employee_id))

    employee_id = request.args.get(
        'employee_id') or employee_shift_data['employee_shift'].employee_id
    
    print(f"shift_start_time {shift_start_time}")
    print(f"shift_end_time {shift_end_time}")
    print(f"actual_start_time {actual_start_time}")
    print(f"actual_end_time {actual_end_time}")

    return render_template(
        'my_shifts/edit_times.html',
        shift_name=employee_shift_data['shift_name'],
        employee_shift=employee_shift_data['employee_shift'],
        employee_id=employee_id,
        shift_start_time=shift_start_time,
        shift_end_time=shift_end_time,
        actual_start_time=actual_start_time,
        actual_end_time=actual_end_time
        )

    
@my_shifts_bp.route('/select_month', methods=['POST'])
def select_month():
    selected_date = datetime.strptime(request.form['selected_date'], '%Y-%m-%d')
    current_date = datetime.now()
    month_offset = (selected_date.isocalendar()[1] - current_date.isocalendar()[1])
    return redirect(url_for('my_shifts.index', month_offset=month_offset))

app/templates/my_shifts/edit_my_shift.html
<!-- templates/my_shifts/edit_my_shift.html -->

{% extends 'layout.html' %}

{% block title %}<h1>Edit my Shift</h1>{% endblock %}

{% block content %}
<form action="{{ url_for('my_shifts.edit_assignment', id=employee_shift.employee_shift.id) }}" method="post">
    <div class="form-group">
        <select name="employee_id" required>
            <option value="employee.id">{{current_user.username}}</option>
        </select>
        <select name="shift_id" required>
            {% for shift in shifts %}
                <option value="{{ shift.id }}" {% if shift.id == employee_shift.employee_shift.shift_id %}selected{% endif %}>
                    {{ shift.name }}
                </option>
            {% endfor %}
        </select>
        <input type="date" name="date" value="{{ employee_shift.employee_shift.date }}" required>
    <button type="submit">Update Assignment</button>
    <a href="{{ url_for('my_shifts.index', employee_id=employee_id) }}" class="cancel-button">Cancel</a>
</form>
{% endblock %}

app/templates/my_shifts/edit_times.html
<!-- templates/my_shifts/edit_times.html -->

{% extends 'layout.html' %}

{% block title %}<h1>Edit times</h1>{% endblock %}

{% block content %}
<form action="{{ url_for('my_shifts.update_actual_times', id=employee_shift.id) }}" method="post">
    <div class="form-group">
        <input type="hidden" name="employee_id" value="{{ employee_id }}">
        
        <p>Shift: {{ shift_name }} </p>
        <p>Usual Start and End Time: {{ shift_start_time }}  - {{ shift_end_time }}</p>
        
        <div>
            <label for="actual_start_time">Actual Start Time:</label>
            <input type="time" name="actual_start_time" value="{{ actual_start_time or shift_start_time }}">
        </div> 
        <div>
            <label for="actual_start_time">Actual End Time:</label>
            <input type="time" name="actual_end_time" value="{{ actual_end_time or shift_end_time}}">
        </div>
    </div>
    <button type="submit">Update Times</button>
    <a href="{{ url_for('my_shifts.index', employee_id=employee_id) }}" class="cancel-button">Cancel</a>
</form>
{% endblock %}

app/templates/my_shifts/my_shifts.html
{% extends 'layout.html' %}

{% block title %} <h1>My Shifts</h1> {% endblock %}

{% block content %}

<h2>Welcome {{employee.fullname}}</h2>
<p>You can edit your own shifts and provide the time you did for each of them</p>

<h2>Total Overtime: {{ employee_shifts.total_overtime }}</h2>

{% include 'my_shifts/my_shifts_board.html' %}

<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Employee</th>
            <th>Shift</th>
            <th>Actual Start Time</th>
            <th>Actual End Time</th>
            <th>Overtime Hours</th>
            <th>Edit Actual Times</th>
            <th>Approval Status</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for data in employee_shifts.shifts %}
            <tr>
                <td>{{ data.employee_shift.date }}</td>
                <td>{{ data.employee_name }}</td>
                <td>{{ data.shift_name }}</td>
                <td>{{ data.employee_shift.actual_start_time }}</td>
                <td>{{ data.employee_shift.actual_end_time }}</td>
                <td>{{ data.employee_shift.format_overtime() }}</td>
                <td class="edit-time-column">
                    <a href="{{ url_for('my_shifts.update_actual_times', id=data.employee_shift.id) }}" class="yellow-button" title="Edit Time">Edit time</a>
                </td>
                <td>
                    {% if data.shift_name.upper() in ['OFF', 'REST'] %}
                        {% if data.employee_shift.approval_status == 'Pending' %}
                            <span class="status-pending">Pending</span>
                        {% elif data.employee_shift.approval_status == 'Approved' %}
                            <span class="status-approved">Approved</span>
                        {% elif data.employee_shift.approval_status == 'Rejected' %}
                            <span class="status-rejected">Rejected</span>
                        {% endif %}
                    {% else %}
                        <span>Approved</span>
                    {% endif %}
                </td>
                <td class="action-column">
                    <a href="{{ url_for('my_shifts.edit_assignment', id=data.employee_shift.id) }}" class="edit-button" title="Edit">Edit</a>
                </td>
                <td class="action-column">
                    <a href="{{ url_for('my_shifts.delete_assignment', id=data.employee_shift.id, employee_id=current_user.employee_id) }}" title="Delete"
                    onclick="return confirm('Are you sure you want to delete this {{ data.shift_name }} for {{ data.employee_name }}?');" class="delete-button">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/my_shifts/my_shifts_board.html
<!-- templates/my_shifts/my_shifts_board.html -->

<div class="board-navigation">
    <form action="{{ url_for('my_shifts.select_month') }}" method="post">
        <input type="date" name="selected_date" required onchange="this.form.submit()">
        <a href="{{ url_for('my_shifts.index', month_offset=0) }}" class="nav-button">Current month</a>
    </form>
    <div>
        <a href="{{ url_for('my_shifts.index', month_offset=month_offset-1) }}" class="nav-button">&lt; Previous</a>
        <span>{{ target_date.strftime('%B %Y') }}</span>
        <a href="{{ url_for('my_shifts.index', month_offset=month_offset+1) }}" class="nav-button">Next &gt;</a>
    </div>
</div>

<div class="board">
    <table>
        <thead>
            <tr>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
                <th>Saturday</th>
                <th>Sunday</th>
            </tr>
        </thead>
        <tbody>
            {% for week in calendar_weeks %}
                <tr>
                    {% for day in week %}
                        <td class="{% if day.month != target_date.month %} other-month {% endif %}">
                            <div class="date">{{ day.day }}</div>
                            <div class="
                                {% if day.month != target_date.month %} other-month {% endif %}
                                {% if day.strftime('%Y-%m-%d') in shifts_by_date %}
                                    {% if shifts_by_date[day.strftime('%Y-%m-%d')]['request_status'] in ['PENDING', 'REQUESTED'] %}
                                        pending-approval
                                    {% elif shifts_by_date[day.strftime('%Y-%m-%d')]['request_status'] == 'REJECTED' %}
                                        rejected-shift
                                    {% endif %}
                                {% endif %}
                                "
                                style="
                                    padding: 0px; 
                                    background-color: 
                                        {% if day.strftime('%Y-%m-%d') in shifts_by_date %}
                                            {{ shifts_by_date[day.strftime('%Y-%m-%d')]['bg_color'] }}
                                        {% endif %}; 
                                    color: 
                                        {% if day.strftime('%Y-%m-%d') in shifts_by_date %}
                                            {{ shifts_by_date[day.strftime('%Y-%m-%d')]['text_color'] }}
                                        {% endif %}
                                    "
                            >
                                <form method="POST" action="{{ url_for('my_shifts.assign_shift', month_offset=month_offset) }}" class="in_table">
                                    <input type="hidden" name="employee_id" value="{{ current_user.employee_id }}">
                                    <input type="hidden" name="date" value="{{ day.strftime('%Y-%m-%d') }}">
                                    <input type="hidden" name="month_offset" value="{{ month_offset }}">
                                    <select name="shift_id" onchange="this.form.submit()" class="in_board">
                                        <option value=""> </option>
                                        {% for shift in shifts %}
                                            <option value="{{ shift.id }}"
                                                    {% if day.strftime('%Y-%m-%d') in shifts_by_date and shifts_by_date[day.strftime('%Y-%m-%d')]['name'] == shift.name %}
                                                        selected
                                                    {% endif %}
                                                    style="background-color: {{ shift.bg_color }}; color: {{ shift.text_color }}">
                                                {{ shift.name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </form>
                            </div>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>